### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by riverar** [juhasch/pyBusPirateLite#10]
Using latest master. Looks like this requires Python 3, might be worth noting.

```
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyBusPirateLite.I2C import *
>>> I2C()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyBusPirateLite\I2C.py", line 55, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by juhasch** [comment]
You are correct, I assume Python 3. Thanks for noticing, I will add a note.

**Comment by riverar** [comment]
Heads up: I ran into other problems and ultimately abandoned this project. Doesn't seem to work properly at all, might be worth testing when you have some free time.

**Comment by averri** [comment]
That's true, @riverar. This is a great project, unfortunately, it has few blocking issues.

**Comment by juhasch** [comment]
Should work now.
